### PR TITLE
14 [6.0 PT] - Add tests for reservation

### PR DESCRIPTION
**Pull request by felixodette**
Created tests for reservations.

### CODE REVIEW

**Review by huseyinbiyik — CHANGES_REQUESTED** [review]
Hi @felixodette . Good job but we use RSpec for testing because @ahzamir will use swagger with RSpec and we used only RSpec during the curriculum.

**Comment by felixodette** [comment]
Thanks @huseyinbiyik , will get the test written in rspec shortly.

**Comment by felixodette** [comment]
@huseyinbiyik reservation spec created for your review.

**Comment by huseyinbiyik** [comment]
Hey @felixodette. On this project [User](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md#:~:text=The%20user%20logs%20in%20to%20the%20website%2C%20only%20by%20typing%20the%20username) has only name attribute. So when I run the test I get the error below. 
Screen Shot 2022-10-03 at 8 42 08 AM

**Comment by felixodette** [comment]
@huseyinbiyik thanks for the quick review. Reservations tests now in RSpec. Aluta Continua Brother!

**Review by huseyinbiyik — APPROVED** [review]
Hey @felixodette,

Tests are passing. Congrats 🎉

OPTIONAL: I recommend you to move your model test under spec/model folder instead of test/models so, in that case we can be more organized. 🛤

Good job, you can merge it! 🧩

**Comment by felixodette** [comment]
Hey @huseyinbiyik , moved the file to the appropriate folder. Thanks for pointing that out.

**Pull request merged**
